### ISSUE TITLE
add outside-gesture-recognizer

### ISSUE THREAD

**Issue by pbodsk** [nodes-ios/Drawer#4]
We need to be able to dismiss the drawer by tapping on the dimmed background outside the drawer.

**Comment by kjoneandrei** [comment]
@pbodsk should be solved in https://github.com/nodes-ios/Drawer/pull/5

**Comment by pbodsk** [comment]
@kjoneandrei OK nice work 👍 

I was just transferring the issue from our Squads repo, so now we can close it twice 😄 

The PR and this issue seems to relate now, so when we close the PR, we can close this issue as well.

**Comment by kjoneandrei** [comment]
fixed in https://github.com/nodes-ios/Drawer/releases/tag/v1.0.1
